title: Bright Solar Resource Model
description: The Bright Solar Resource Model as published in the Journal of Solar Energy
google_analytics: UA-60915865-1
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
