title: Bright Solar Model
description: The Bright Solar Models (SIG and SDSIG) as published in the Journal of Solar Energy
google_analytics: UA-60915865-1
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
